version: '3'

services:
    bot:
        image: iudmitriev/telegram_bot:main
        labels:
            - "com.centurylinklabs.watchtower.scope=myscope"
        environment:
            BOT_TOKEN: ${BOT_AUTH_TOKEN}

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 60 --scope myscope
        labels:
            - "com.centurylinklabs.watchtower.scope=myscope"

